# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            CoderOnCode 
email:            contact@coderoncode.com
description:      Random ramblings about code, programming, and technology
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://coderoncode.com' # The base hostname & protocol for your site
github_username:  CoderOnCode 
twitter_username: CoderOnCode 

markdown:  kramdown
permalink: pretty
paginate:  12


jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved

gems:
  - jekyll-paginate
  - jekyll/tagging
  - classifier-reborn

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  allanmacgregor:
    name:             Allan MacGregor 
    bio:              Director of Engineering at Demac Media, veteran software developer constantly exploring new tools and technologies. 
    gravatar:         https://s.gravatar.com/avatar/b64d0da0dffd4028635446e4cfbc0cee?s=150
    email:            info@allanmacgregor.com
    website:          http://coderoncode.com
    github_username:  amacgregor 
    twitter_username: allanmacgregor
